name: linli
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  dio: ^3.0.3
  shared_preferences: ^0.5.3+4
  flukit: ^1.0.0
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/images/well.jpg
  fonts:
    - family: kaiti
      fonts:
        # https://fonts.google.com/specimen/Noto+Sans+TC -->对应字体下载地址 这里可以不填 只是注释
        - asset: asset/fonts/楷体GB2312.ttf